"""Install the marimo kernelspec so Zed (and Jupyter) can find it."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path

from jupyter_client.kernelspec import KernelSpecManager

REPO_ROOT = Path(__file__).resolve().parent.parent
GITHUB_SOURCE = "git+https://github.com/hermabr/marimo.zed"

SHIM_MARKER = "# marimo-zed-shim"

# Zed never reads Jupyter kernelspecs in SSH remote projects: whichever Python
# toolchain you pick in the kernel picker, its headless server runs
# `<python> -m ipykernel_launcher -f <connection_file>` with the project root
# as the working directory. Python puts that working directory ahead of
# site-packages on sys.path for `-m`, so a file named ipykernel_launcher.py in
# the project root shadows ipykernel's real launcher and redirects the launch
# into marimo-zed.
SHIM_TEMPLATE = '''{marker}
"""Redirect Zed's SSH remote REPL kernel into marimo-zed.

Zed ignores Jupyter kernelspecs in SSH remote projects and always launches
`<toolchain python> -m ipykernel_launcher -f <connection_file>` from the
project root. The project root precedes site-packages on sys.path, so this
file shadows ipykernel's launcher and starts the marimo kernel instead.

Set MARIMO_ZED_DISABLE=1 to fall through to the real ipykernel.

Generated by `marimo-zed-install --ssh-shim`; do not edit by hand.
"""

import os
import runpy
import sys

UV = {uv!r}
SOURCE_ARGS = {source_args!r}
EXECUTION = {execution!r}

SHIM_DIR = os.path.dirname(os.path.abspath(__file__))


def fall_through_to_ipykernel():
    sys.path = [
        p
        for p in sys.path
        if os.path.abspath(p if p else os.getcwd()) != SHIM_DIR
    ]
    runpy.run_module("ipykernel_launcher", run_name="__main__", alter_sys=True)


def main():
    if os.environ.get("MARIMO_ZED_DISABLE"):
        fall_through_to_ipykernel()
        return
    uv = UV if os.path.exists(UV) else "uv"
    os.environ.setdefault("MARIMO_ZED_EXECUTION", EXECUTION)
    os.environ.setdefault("MARIMO_ZED_UV", uv)
    argv = [uv, "run", *SOURCE_ARGS, "python", "-m", "marimo_zed", *sys.argv[1:]]
    os.execvp(argv[0], argv)


if __name__ == "__main__":
    main()
'''


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install the marimo Jupyter kernelspec"
    )
    parser.add_argument(
        "--name", default="marimo", help="kernelspec name (default: marimo)"
    )
    parser.add_argument(
        "--display-name",
        default="marimo (reactive)",
        help="display name shown in kernel pickers",
    )
    parser.add_argument(
        "--uv",
        default="uv",
        help="uv executable to put in the kernelspec (default: uv)",
    )
    parser.add_argument(
        "--execution",
        choices=("eager", "lazy"),
        default="eager",
        help="default execution mode: eager reruns changed cells when the "
        "notebook file is saved, lazy queues them until the next execution "
        "(default: eager; toggle at runtime with a `# marimo: lazy` cell)",
    )
    parser.add_argument(
        "--source",
        default=None,
        help="where the kernelspec gets marimo-zed from: a local directory "
        "(installed editable) or a uv requirement such as "
        f"{GITHUB_SOURCE} (default: this checkout when run from one, "
        "else the GitHub repo)",
    )
    parser.add_argument(
        "--ssh-shim",
        nargs="?",
        const=".",
        default=None,
        metavar="DIR",
        help="instead of a kernelspec, write an ipykernel_launcher.py shim "
        "into DIR (default: the current directory). Run this in a project's "
        "root on a machine you open over SSH with Zed, which never reads "
        "kernelspecs there; the shim redirects any Python toolchain you pick "
        "in Zed's kernel picker into marimo-zed",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="with --ssh-shim, overwrite an existing ipykernel_launcher.py "
        "that this tool did not generate",
    )
    args = parser.parse_args()

    if args.source is not None:
        source = args.source
    elif (REPO_ROOT / "pyproject.toml").is_file():
        # Running from a checkout (e.g. `uv run marimo-zed-install`).
        source = str(REPO_ROOT)
    else:
        # Running from an installed package (e.g. `uvx --from git+... marimo-zed-install`),
        # where REPO_ROOT is a site-packages directory that uv cannot install from.
        source = GITHUB_SOURCE
    if Path(source).is_dir():
        with_args = ["--with-editable", str(Path(source).resolve())]
    else:
        with_args = ["--with", source]

    if args.ssh_shim is not None:
        install_ssh_shim(args, with_args)
        return

    # The kernel is launched with `uv run` from the directory Zed opened, so
    # both the kernel process and user code run in that project's environment,
    # with marimo-zed and its dependencies layered on top.
    spec = {
        "argv": [
            args.uv,
            "run",
            *with_args,
            "python",
            "-m",
            "marimo_zed",
            "-f",
            "{connection_file}",
        ],
        "display_name": args.display_name,
        "language": "python",
        "interrupt_mode": "signal",
        "env": {"MARIMO_ZED_EXECUTION": args.execution},
        "metadata": {"debugger": False},
    }

    with tempfile.TemporaryDirectory() as td:
        (Path(td) / "kernel.json").write_text(json.dumps(spec, indent=2))
        dest = KernelSpecManager().install_kernel_spec(
            td, kernel_name=args.name, user=True
        )
    print(f"Installed kernelspec '{args.name}' to {dest}")


def install_ssh_shim(args: argparse.Namespace, with_args: list[str]) -> None:
    dest_dir = Path(args.ssh_shim).resolve()
    if not dest_dir.is_dir():
        sys.exit(f"error: {dest_dir} is not a directory")
    dest = dest_dir / "ipykernel_launcher.py"

    if dest.exists() and not args.force:
        first_line = dest.read_text().split("\n", 1)[0]
        if first_line != SHIM_MARKER:
            sys.exit(
                f"error: {dest} exists and was not generated by this tool; "
                "pass --force to overwrite it"
            )

    # Resolve uv now: the shim later runs under Zed's headless server, whose
    # PATH may not include uv's install location.
    uv = shutil.which(args.uv) or args.uv

    dest.write_text(
        SHIM_TEMPLATE.format(
            marker=SHIM_MARKER,
            uv=uv,
            source_args=with_args,
            execution=args.execution,
        )
    )
    print(f"Installed Zed SSH shim to {dest}")
    print(
        "In Zed, pick any Python toolchain in the REPL kernel picker for this "
        "project; the shim redirects it to marimo-zed."
    )


if __name__ == "__main__":
    main()
