"""Install the marimo kernelspec so Zed (and Jupyter) can find it."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path

from jupyter_client.kernelspec import KernelSpecManager

REPO_ROOT = Path(__file__).resolve().parent.parent
GITHUB_SOURCE = "git+https://github.com/hermabr/marimo.zed"

SHIM_MARKER = "# marimo-zed-shim"

# Zed never reads Jupyter kernelspecs in SSH remote projects: whichever Python
# toolchain you pick in the kernel picker, its headless server runs
# `<python> -m ipykernel_launcher -f <connection_file>` with the project root
# as the working directory. Python puts that working directory ahead of
# site-packages on sys.path for `-m`, so a file named ipykernel_launcher.py in
# the project root shadows ipykernel's real launcher and redirects the launch
# into marimo-zed.
SHIM_TEMPLATE = '''# marimo-zed-shim
"""Redirect Zed's SSH remote REPL kernel into marimo-zed.

Zed ignores Jupyter kernelspecs in SSH remote projects and always launches
`<toolchain python> -m ipykernel_launcher -f <connection_file>` from the
project root. The project root precedes site-packages on sys.path, so this
file shadows ipykernel's launcher and starts the marimo kernel instead.

Zed attempts to connect before kernels launched through uv are ready. This
shim binds Zed's five ports immediately, starts marimo on alternate ports,
and proxies the TCP streams once the real kernel is listening.

Set MARIMO_ZED_DISABLE=1 to fall through to the real ipykernel.

Generated by `marimo-zed-install --ssh-shim`; do not edit by hand.
"""

import ctypes
import json
import os
import runpy
import select
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time

UV = __MARIMO_ZED_UV__
SOURCE_ARGS = __MARIMO_ZED_SOURCE_ARGS__
EXECUTION = __MARIMO_ZED_EXECUTION__

SHIM_DIR = os.path.dirname(os.path.abspath(__file__))
CHANNELS = ("shell", "iopub", "stdin", "control", "hb")
CONNECT_RETRY_SECONDS = 0.02


def fall_through_to_ipykernel():
    sys.path = [
        p
        for p in sys.path
        if os.path.abspath(p if p else os.getcwd()) != SHIM_DIR
    ]
    runpy.run_module("ipykernel_launcher", run_name="__main__", alter_sys=True)


def connection_file_argument(argv):
    for index, arg in enumerate(argv):
        if arg in ("-f", "--f") and index + 1 < len(argv):
            return index + 1, argv[index + 1]
        if arg.startswith("--f="):
            return index, arg.split("=", 1)[1]
    raise SystemExit("marimo-zed SSH shim requires a connection file (-f PATH)")


def listen(host, port):
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    listener.bind((host, port))
    listener.listen()
    listener.settimeout(0.2)
    return listener


def unused_ports(host):
    probes = []
    try:
        for channel in CHANNELS:
            probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            probe.bind((host, 0))
            probes.append(probe)
        return {
            channel: probe.getsockname()[1]
            for channel, probe in zip(CHANNELS, probes)
        }
    finally:
        for probe in probes:
            probe.close()


def child_dies_with_parent():
    """Ask Linux to terminate uv if this supervisor is killed by Zed."""
    if not sys.platform.startswith("linux"):
        return
    libc = ctypes.CDLL(None, use_errno=True)
    if libc.prctl(1, signal.SIGTERM) != 0:  # PR_SET_PDEATHSIG
        raise OSError(ctypes.get_errno(), "prctl(PR_SET_PDEATHSIG) failed")
    # The parent may have exited between fork and prctl.
    if os.getppid() == 1:
        os.kill(os.getpid(), signal.SIGTERM)


class Proxy:
    def __init__(self, host, listeners, back_ports, child):
        self.host = host
        self.back_ports = back_ports
        self.child = child
        self.stopping = threading.Event()
        self.listeners = listeners
        self.connections = set()
        self.connections_lock = threading.Lock()

    def start(self):
        for channel in CHANNELS:
            threading.Thread(
                target=self.accept_connections,
                args=(channel,),
                name=f"marimo-zed-{channel}-proxy",
                daemon=True,
            ).start()

    def accept_connections(self, channel):
        listener = self.listeners[channel]
        while not self.stopping.is_set():
            try:
                frontend, _ = listener.accept()
            except socket.timeout:
                continue
            except OSError:
                return
            threading.Thread(
                target=self.proxy_connection,
                args=(frontend, self.back_ports[channel]),
                daemon=True,
            ).start()

    def frontend_closed(self, frontend):
        try:
            readable, _, _ = select.select([frontend], [], [], 0)
            return bool(readable) and frontend.recv(1, socket.MSG_PEEK) == b""
        except OSError:
            return True

    def connect_backend(self, frontend, port):
        while not self.stopping.is_set() and self.child.poll() is None:
            if self.frontend_closed(frontend):
                return None
            backend = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            backend.settimeout(CONNECT_RETRY_SECONDS)
            try:
                backend.connect((self.host, port))
                backend.settimeout(None)
                return backend
            except OSError:
                backend.close()
                time.sleep(CONNECT_RETRY_SECONDS)
        return None

    def track(self, *sockets):
        with self.connections_lock:
            self.connections.update(sockets)

    def untrack(self, *sockets):
        with self.connections_lock:
            for stream in sockets:
                self.connections.discard(stream)

    def proxy_connection(self, frontend, back_port):
        backend = self.connect_backend(frontend, back_port)
        if backend is None:
            frontend.close()
            return
        self.track(frontend, backend)
        upstream = threading.Thread(
            target=self.copy_stream,
            args=(frontend, backend),
            daemon=True,
        )
        upstream.start()
        self.copy_stream(backend, frontend)
        upstream.join(timeout=1)
        self.untrack(frontend, backend)
        frontend.close()
        backend.close()

    @staticmethod
    def copy_stream(source, destination):
        try:
            while data := source.recv(65536):
                destination.sendall(data)
        except OSError:
            pass
        finally:
            try:
                destination.shutdown(socket.SHUT_WR)
            except OSError:
                pass

    def stop(self):
        self.stopping.set()
        for listener in self.listeners.values():
            listener.close()
        with self.connections_lock:
            connections = list(self.connections)
            self.connections.clear()
        for stream in connections:
            stream.close()


def write_backend_connection_file(connection_info):
    backend_info = dict(connection_info)
    host = backend_info.get("ip", "127.0.0.1")
    backend_ports = unused_ports(host)
    for channel, port in backend_ports.items():
        backend_info[f"{channel}_port"] = port
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        prefix="marimo-zed-kernel-",
        suffix=".json",
        delete=False,
    )
    try:
        json.dump(backend_info, handle)
    finally:
        handle.close()
    os.chmod(handle.name, 0o600)
    return handle.name, backend_info


def proxied_main():
    connection_arg, connection_file = connection_file_argument(sys.argv[1:])
    with open(connection_file) as handle:
        connection_info = json.load(handle)
    if connection_info.get("transport", "tcp") != "tcp":
        raise SystemExit("marimo-zed SSH shim only supports TCP connections")
    host = connection_info.get("ip", "127.0.0.1")
    front_ports = {
        channel: int(connection_info[f"{channel}_port"]) for channel in CHANNELS
    }

    # Bind Zed's ports before starting uv. An SSH forward can now stay open
    # while the slower backend kernel imports and binds its alternate ports.
    listeners = {
        channel: listen(host, front_ports[channel]) for channel in CHANNELS
    }
    backend_file = None
    proxy = None
    child = None
    try:
        backend_file, backend_info = write_backend_connection_file(connection_info)
        child_args = list(sys.argv[1:])
        original_arg = child_args[connection_arg]
        child_args[connection_arg] = (
            f"--f={backend_file}" if original_arg.startswith("--f=") else backend_file
        )
        uv = UV if os.path.exists(UV) else "uv"
        os.environ.setdefault("MARIMO_ZED_EXECUTION", EXECUTION)
        os.environ.setdefault("MARIMO_ZED_UV", uv)
        argv = [uv, "run", *SOURCE_ARGS, "python", "-m", "marimo_zed", *child_args]
        popen_options = (
            {"preexec_fn": child_dies_with_parent} if os.name == "posix" else {}
        )
        child = subprocess.Popen(argv, **popen_options)

        back_ports = {
            channel: int(backend_info[f"{channel}_port"]) for channel in CHANNELS
        }
        proxy = Proxy(host, listeners, back_ports, child)
        proxy.start()

        def forward_signal(signum, _frame):
            if child.poll() is None:
                child.send_signal(signum)

        signal.signal(signal.SIGINT, forward_signal)
        signal.signal(signal.SIGTERM, forward_signal)
        return child.wait()
    finally:
        if proxy is not None:
            proxy.stop()
        else:
            for listener in listeners.values():
                listener.close()
        if child is not None and child.poll() is None:
            child.terminate()
            try:
                child.wait(timeout=5)
            except subprocess.TimeoutExpired:
                child.kill()
                child.wait()
        if backend_file is not None:
            try:
                os.unlink(backend_file)
            except FileNotFoundError:
                pass


def main():
    if os.environ.get("MARIMO_ZED_DISABLE"):
        fall_through_to_ipykernel()
        return 0
    return proxied_main()


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install the marimo Jupyter kernelspec"
    )
    parser.add_argument(
        "--name", default="marimo", help="kernelspec name (default: marimo)"
    )
    parser.add_argument(
        "--display-name",
        default="marimo (reactive)",
        help="display name shown in kernel pickers",
    )
    parser.add_argument(
        "--uv",
        default="uv",
        help="uv executable to put in the kernelspec (default: uv)",
    )
    parser.add_argument(
        "--execution",
        choices=("eager", "lazy"),
        default="eager",
        help="default execution mode: eager reruns changed cells when the "
        "notebook file is saved, lazy queues them until the next execution "
        "(default: eager; toggle at runtime with a `# marimo: lazy` cell)",
    )
    parser.add_argument(
        "--source",
        default=None,
        help="where the kernelspec gets marimo-zed from: a local directory "
        "(installed editable) or a uv requirement such as "
        f"{GITHUB_SOURCE} (default: this checkout when run from one, "
        "else the GitHub repo)",
    )
    parser.add_argument(
        "--ssh-shim",
        nargs="?",
        const=".",
        default=None,
        metavar="DIR",
        help="instead of a kernelspec, write an ipykernel_launcher.py shim "
        "into DIR (default: the current directory). Run this in a project's "
        "root on a machine you open over SSH with Zed, which never reads "
        "kernelspecs there; the shim redirects any Python toolchain you pick "
        "in Zed's kernel picker into marimo-zed",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="with --ssh-shim, overwrite an existing ipykernel_launcher.py "
        "that this tool did not generate",
    )
    args = parser.parse_args()

    if args.source is not None:
        source = args.source
    elif (REPO_ROOT / "pyproject.toml").is_file():
        # Running from a checkout (e.g. `uv run marimo-zed-install`).
        source = str(REPO_ROOT)
    else:
        # Running from an installed package (e.g. `uvx --from git+... marimo-zed-install`),
        # where REPO_ROOT is a site-packages directory that uv cannot install from.
        source = GITHUB_SOURCE
    if Path(source).is_dir():
        with_args = ["--with-editable", str(Path(source).resolve())]
    else:
        with_args = ["--with", source]

    if args.ssh_shim is not None:
        install_ssh_shim(args, with_args)
        return

    # The kernel is launched with `uv run` from the directory Zed opened, so
    # both the kernel process and user code run in that project's environment,
    # with marimo-zed and its dependencies layered on top.
    spec = {
        "argv": [
            args.uv,
            "run",
            *with_args,
            "python",
            "-m",
            "marimo_zed",
            "-f",
            "{connection_file}",
        ],
        "display_name": args.display_name,
        "language": "python",
        "interrupt_mode": "signal",
        "env": {"MARIMO_ZED_EXECUTION": args.execution},
        "metadata": {"debugger": False},
    }

    with tempfile.TemporaryDirectory() as td:
        (Path(td) / "kernel.json").write_text(json.dumps(spec, indent=2))
        dest = KernelSpecManager().install_kernel_spec(
            td, kernel_name=args.name, user=True
        )
    print(f"Installed kernelspec '{args.name}' to {dest}")


def install_ssh_shim(args: argparse.Namespace, with_args: list[str]) -> None:
    dest_dir = Path(args.ssh_shim).resolve()
    if not dest_dir.is_dir():
        sys.exit(f"error: {dest_dir} is not a directory")
    dest = dest_dir / "ipykernel_launcher.py"

    if dest.exists() and not args.force:
        first_line = dest.read_text().split("\n", 1)[0]
        if first_line != SHIM_MARKER:
            sys.exit(
                f"error: {dest} exists and was not generated by this tool; "
                "pass --force to overwrite it"
            )

    # Resolve uv now: the shim later runs under Zed's headless server, whose
    # PATH may not include uv's install location.
    uv = shutil.which(args.uv) or args.uv

    shim = SHIM_TEMPLATE.replace("__MARIMO_ZED_UV__", repr(uv))
    shim = shim.replace("__MARIMO_ZED_SOURCE_ARGS__", repr(with_args))
    shim = shim.replace("__MARIMO_ZED_EXECUTION__", repr(args.execution))
    dest.write_text(shim)
    print(f"Installed Zed SSH shim to {dest}")
    print(
        "In Zed, pick any Python toolchain in the REPL kernel picker for this "
        "project; the shim redirects it to marimo-zed."
    )


if __name__ == "__main__":
    main()
