"""Tests for the Zed SSH shim: `python -m ipykernel_launcher` run from a
project root containing the shim must launch marimo-zed, not ipykernel."""

from __future__ import annotations

import json
import os
import stat
import subprocess
import sys

import pytest

from marimo_zed.install import REPO_ROOT, SHIM_MARKER, main

TIMEOUT = 30


def install_shim(project_dir, monkeypatch, *extra_args):
    monkeypatch.setattr(
        sys, "argv", ["marimo-zed-install", "--ssh-shim", str(project_dir), *extra_args]
    )
    main()
    return project_dir / "ipykernel_launcher.py"


@pytest.fixture
def fake_uv(tmp_path):
    """A uv stand-in that dumps its argv and environment as JSON."""
    path = tmp_path / "bin" / "uv"
    path.parent.mkdir()
    path.write_text(
        f"#!{sys.executable}\n"
        "import json, os, sys\n"
        "print(json.dumps({\n"
        "    'argv': sys.argv[1:],\n"
        "    'execution': os.environ.get('MARIMO_ZED_EXECUTION'),\n"
        "    'uv': os.environ.get('MARIMO_ZED_UV'),\n"
        "}))\n"
    )
    path.chmod(path.stat().st_mode | stat.S_IXUSR)
    return path


def test_install_writes_marked_shim(tmp_path, monkeypatch):
    shim = install_shim(tmp_path, monkeypatch)
    text = shim.read_text()
    assert text.startswith(SHIM_MARKER + "\n")
    # Running from a checkout, the shim references this repo editable.
    assert str(REPO_ROOT) in text


def test_shim_hijacks_ipykernel_launcher(tmp_path, monkeypatch, fake_uv):
    project = tmp_path / "project"
    project.mkdir()
    install_shim(project, monkeypatch, "--uv", str(fake_uv))

    # Exactly what Zed's headless server runs on the remote host.
    out = subprocess.run(
        [sys.executable, "-m", "ipykernel_launcher", "-f", "conn.json"],
        cwd=project,
        capture_output=True,
        text=True,
        timeout=TIMEOUT,
    )
    assert out.returncode == 0, out.stderr
    report = json.loads(out.stdout)
    assert report["argv"] == [
        "run",
        "--with-editable",
        str(REPO_ROOT),
        "python",
        "-m",
        "marimo_zed",
        "-f",
        "conn.json",
    ]
    assert report["execution"] == "eager"
    assert report["uv"] == str(fake_uv)


def test_shim_respects_execution_flag(tmp_path, monkeypatch, fake_uv):
    install_shim(tmp_path, monkeypatch, "--uv", str(fake_uv), "--execution", "lazy")
    out = subprocess.run(
        [sys.executable, "-m", "ipykernel_launcher", "-f", "conn.json"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        timeout=TIMEOUT,
    )
    assert out.returncode == 0, out.stderr
    assert json.loads(out.stdout)["execution"] == "lazy"


def test_disable_env_falls_through_to_real_launcher(tmp_path, monkeypatch, fake_uv):
    """MARIMO_ZED_DISABLE strips the shim off sys.path and runs the real
    module (simulated here by a launcher further down sys.path)."""
    project = tmp_path / "project"
    project.mkdir()
    install_shim(project, monkeypatch, "--uv", str(fake_uv))

    site = tmp_path / "site"
    site.mkdir()
    (site / "ipykernel_launcher.py").write_text("print('real launcher ran')\n")

    env = os.environ | {"MARIMO_ZED_DISABLE": "1", "PYTHONPATH": str(site)}
    out = subprocess.run(
        [sys.executable, "-m", "ipykernel_launcher", "-f", "conn.json"],
        cwd=project,
        capture_output=True,
        text=True,
        timeout=TIMEOUT,
        env=env,
    )
    assert out.returncode == 0, out.stderr
    assert out.stdout.strip() == "real launcher ran"


def test_refuses_to_overwrite_foreign_file(tmp_path, monkeypatch):
    launcher = tmp_path / "ipykernel_launcher.py"
    launcher.write_text("# someone else's file\n")
    with pytest.raises(SystemExit, match="not generated by this tool"):
        install_shim(tmp_path, monkeypatch)
    assert launcher.read_text() == "# someone else's file\n"

    install_shim(tmp_path, monkeypatch, "--force")
    assert launcher.read_text().startswith(SHIM_MARKER)

    # Re-installing over our own shim needs no --force.
    install_shim(tmp_path, monkeypatch, "--execution", "lazy")
    assert "lazy" in launcher.read_text()


def test_rejects_missing_directory(tmp_path, monkeypatch):
    with pytest.raises(SystemExit, match="is not a directory"):
        install_shim(tmp_path / "missing", monkeypatch)
